
name: Build Linux Plugin

on:
  workflow_dispatch:
    inputs:
      CLIENT:
        description: 'customization folder name'
        required: true


jobs:
  build-linux-model:
    runs-on: ubuntu-22.04  # specific version because swift and static swift sdk depend on specfic version of ubuntu
    steps:
      - name: Install dependencias for swift compiler  # https://www.swift.org/install/linux/tarball/  Instructions depends on version of Ubuntu
        run: |
          docker pull swift
          docker run --privileged --interactive --tty --name swift-latest swift:latest /bin/bash
          docker start swift-latest
          #docker attach swift-latest
          echo "installing sdk"
          docker exec swift-latest swift sdk install https://download.swift.org/swift-6.0-branch/static-sdk/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-02-a/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1.artifactbundle.tar.gz --checksum 42a361e1a240e97e4bb3a388f2f947409011dcd3d3f20b396c28999e9736df36
          docker logs swift-latest
          echo "trying sdk list"
          docker exec swift-latest swift sdk list
          docker logs swift-latest

