name: Build Linux Plugin

on:
  workflow_dispatch:
    inputs:
      CLIENT:
        description: 'customization folder name'
        required: true


jobs:
  build-linux-model:
    runs-on: ubuntu-22.04  # specific version because swift and static swift sdk depend on specfic version of ubuntu
    steps:
      - name: Install dependencias for swift compiler  # https://www.swift.org/install/linux/tarball/  Instructions depends on version of Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install \
              binutils \
              git \
              gnupg2 \
              libc6-dev \
              libcurl4-openssl-dev \
              libedit2 \
              libgcc-11-dev \
              libpython3-dev \
              libsqlite3-0 \
              libstdc++-11-dev \
              libxml2-dev \
              libz3-dev \
              pkg-config \
              python3-lldb-13 \
              tzdata \
              unzip \
              zlib1g-dev

      - name: Download swift
        run: |
          curl -L -o swift-5.10.1-RELEASE-ubuntu22.04.tar.gz https://download.swift.org/swift-5.10.1-release/ubuntu2204/swift-5.10.1-RELEASE/swift-5.10.1-RELEASE-ubuntu22.04.tar.gz
          curl -L -o swift-5.10.1-RELEASE-ubuntu22.04.tar.gz.sig https://download.swift.org/swift-5.10.1-release/ubuntu2204/swift-5.10.1-RELEASE/swift-5.10.1-RELEASE-ubuntu22.04.tar.gz.sig

      - name: Verify swift
        run: |
          gpg --keyserver hkp://keyserver.ubuntu.com \
              --recv-keys \
              'A62A E125 BBBF BB96 A6E0  42EC 925C C1CC ED3D 1561'\
              'E813 C892 820A 6FA1 3755  B268 F167 DF1A CF9C E069'
          gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
          gpg --verify swift-5.10.1-RELEASE-ubuntu22.04.tar.gz.sig
      
      - name: Install swift 
        run: |
          mkdir temp && tar -xzf swift-5.10.1-RELEASE-ubuntu22.04.tar.gz -C temp
          mv temp/*/* ./  # Mueve los archivos de la carpeta interna al directorio actual
          echo "ls -al"
          ls 
          echo "ls usr"
          ls usr
          echo "ls usr/bin"
          ls -al usr/bin
          echo "ls usr/lib"
          ls -al usr/lib
          echo "ls usr/libexec"
          ls -al usr/libexec
          echo "ls usr/libexec/swift"
          ls -al usr/libexec/swift
          PWD=`pwd`
          SWIFT_PATH="${PWD}/usr/bin"
          export PATH="${SWIFT_PATH}:${PATH}"
          echo "Path: ${PATH}"
          swift --version
          echo "installing sdk"
          swift sdk install https://download.swift.org/swift-6.0-branch/static-sdk/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-02-a/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1.artifactbundle.tar.gz --checksum 42a361e1a240e97e4bb3a388f2f947409011dcd3d3f20b396c28999e9736df36
          swift sdk list
